/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ScoreStorage } from "./ScoreStorage";
export * as factories from "./factories";
export { ScoreStorage__factory } from "./factories/ScoreStorage__factory";
