services:
  waf:
    image: owasp/modsecurity-crs:nginx-alpine
    container_name: waf
    ports:
      - "8080:80"
    restart: always
    networks:
      - app_network
  backend:
    build:
      context: .
      dockerfile: infra/docker/backend/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/backend/src
      - ./backend/data:/app/backend/data
    environment:
      - NODE_ENV=development
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
    command: server -dev -dev-root-token-id="root"
    restart: always
    networks:
      - app_network
volumes:
  backend_data:
networks:
  app_network:
    driver: bridge

