services:
  waf:
    networks:
      - app_network
    image: owasp/modsecurity-crs:nginx-alpine
    container_name: waf
    ports:
      - "80:80"
    restart: always
    volumes:
    # fichier reverse-proxy Nginx
    - ./reverse-proxy/custom.conf:/etc/nginx/conf.d/custom.conf

     # Dossier frontend buildé
    - ./frontend/dist:/usr/share/nginx/html

    #fichier de config ModSecurity
    - ./reverse-proxy/modsecurity.conf:/etc/nginx/modsecurity.conf

    # certificats SSL
    # - ./infra/reverse-proxy/certs:/etc/ssl/certs
    depends_on:
    - api-gateway

  api-gateway:
    abuild:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    networks:
      - app_network
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - AUTH_SERVICE_URL=http://authservice:4000
      - BACKEND_URL=http://backend:3000
      - FRONTEND_URL=http://frontend:80
    depends_on:
      - authservice
      - backend
    restart: always

  dbwriter:
    build:
      context: ./dbwriter
      dockerfile: Dockerfile
    container_name: dbwriter
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/database.sqlite
    volumes:
      - sqlite_data:/app/data
    networks:
      - app_network
    restart: always
    # ports:
    #  - "4000:4000" # test


  backend:
    networks:
      - app_network
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    # ports:
    #   - "3000:3000"
    volumes:
      - sqlite_data:/app/data:ro 
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/database.sqlite
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - NODE_ENV=production
    command: npm run build
    volumes:
      - ./frontend/dist:/app/frontend/dist



  vault:
    image: hashicorp/vault:latest
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    volumes:
      - ./vault/config.hcl:/vault/config/config.hcl
      - vault_data:/vault/file
    command: vault server -config=/vault/config/config.hcl
    restart: always
    networks:
      - app_network


volumes:
  sqlite_data:
  vault_data:

networks:
  app_network:
    driver: bridge

