services:
  waf:
    image: owasp/modsecurity-crs:nginx-alpine
    container_name: waf
    ports:
      - "8080:80"
    restart: always
    networks:
      - app_network
  backend:
    build:
      context: .
      dockerfile: infra/docker/backend/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/backend/src
      - ./backend/data:/app/backend/data
    environment:
      - NODE_ENV=development
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8201:8201"            # Accès web/API Vault
    environment:
      VAULT_ADDR: 'https://0.0.0.0:8201'
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8201","tls_disable":"0", "tls_cert_file":"/data/vault-volume/certificate.pem", "tls_key_file":"/data/vault-volume/key.pem"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
      VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
      VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
    volumes:
      - vault:/data
    cap_add:
      - IPC_LOCK                 # Empêche le swap des secrets en mémoire
    command: server -dev -dev-root-token-id="00000000-0000-0000-0000-000000000000"
    restart: always
    networks:
      - app_network
volumes:
  backend_data:
networks:
  app_network:
    driver: bridge

