services:
  # le service WAF
  waf:
    networks:
      - app_network
    image: owasp/modsecurity-crs:nginx-alpine
    container_name: waf
    ports:
      - "80:80"   # ton site sera dispo sur http://localhost:8080
    restart: always
    volumes:
    # ton fichier reverse-proxy Nginx (Solution A : conf.d)
    - ./infra/reverse-proxy/custom.conf:/etc/nginx/conf.d/custom.conf

    # ton fichier de config ModSecurity
    # - ./infra/reverse-proxy/modsecurity.conf:/etc/nginx/modsecurity.conf

    # certificats SSL
    # - ./infra/reverse-proxy/certs:/etc/ssl/certs
    depends_on:
    - backend

  backend:
    networks:
      - app_network
    build:
      context: .
      dockerfile: infra/docker/backend/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/backend/src
      - ./backend/data:/app/backend/data
    environment:
      - NODE_ENV=development
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
    command: server -dev -dev-root-token-id="root"
    restart: always
    networks:
      - app_network
volumes:
  backend_data:
networks:
  app_network:
    driver: bridge

