services:
  # le service WAF
  waf:
    image: owasp/modsecurity-crs:nginx-alpine
    container_name: waf
    ports:
      - "8080:80"   # ton site sera dispo sur http://localhost:8080
    restart: always
    volumes:
    - ./infra/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./infra/reverse-proxy/modesecurity.conf:/etc/nginx/modsecurity.conf:ro
    - ./infra/reverse-proxy/certs:/etc/ssl/certs:ro
    depends_on:
    - backend

  backend:
    build:
      context: .
      dockerfile: infra/docker/backend/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/backend/src
      - ./backend/data:/app/backend/data
    environment:
      - NODE_ENV=development

volumes:
  backend_data:
 